version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Aa123456!
      MYSQL_DATABASE: system-data   
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: system-app
    depends_on:
      - mysql
    working_dir: /app/server
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      DB_NAME: system-data
      DB_USER: root
      DB_PASS: Aa123456!
      DB_HOST: mysql
    volumes:
      - ./server:/app/server
      - ./client:/app/client
    command: ["./wait-for-it.sh", "mysql:3306", "--", "node", "index.js"]

volumes:
  mysql_data:
